name: nova_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  connectivity_plus: ^7.0.0
  dartssh2: ^2.13.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^8.0.0
  http: ^1.6.0
  intl: ^0.20.2
  network_info_plus: ^7.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  xterm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
